### ISSUE TITLE
[Feature] Macroable TestView

### ISSUE THREAD

**Issue by peterfox** [nunomaduro/laravel-mojito#1]
It would be quite useful to make the [TestView](https://github.com/nunomaduro/laravel-mojito/blob/master/src/TestView.php) class macroable in the same way the TestResponse class is in Laravel's core package. That way if people have particularly complicated testing logic for a view they can add it as a macro.

**Comment by nunomaduro** [comment]
Sounds a good idea. Can you make a pull request adding that feature?

**Comment by peterfox** [comment]
Sure, happy to do so 👍

**Comment by nunomaduro** [comment]
Thanks!
