### ISSUE TITLE
Trying to figure how to "assert not contain"

### ISSUE THREAD

**Issue by beNjiox** [nunomaduro/laravel-mojito#5]
Hey,

Absolutely love this package! Thanks a lot!

I was trying to do something like that

```php
$this->assertView('app.orders.read', ['order' => $order])->doesNotContain('text');

$this->doSomethingThatUpdatesTheOrderSoWeSeeTheText();

$this->assertView('app.orders.read', ['order' => $order])->contains('text');
```

But as you know, `doesNotContain` does not exist.
I thought that would be a pretty decent use case for a Macro, but haven't been successful setting up one.

That's what I tried, but it seems odd (and it doesn't work!)

```php
class ViewAssertionProvider extends ServiceProvider
{
    public function boot()
    {
        ViewAssertion::macro('doesNotContain', function (string $string) {
            return ! $this->contains($string);
        });
    }
}
```

Also, I noticed there is an assert method that could be used somehow `assertStringNotContainsString` in PHPUnit Assert.php, but not sure how to use it.

Any pointers? Happy to PR something, if relevant, once I understand how to solve this.

Thanks again 🙏

**Comment by nunomaduro** [comment]
We don't have that yet, would you like to add that feature?

**Comment by beNjiox** [comment]
It would be useful to me yes! Don't want to "feature creep" the package though. 

What do you think?

If you are fine with the idea, I assume it would be as easy as adding this to `ViewAssertion.php`, correct?

Also what do you think of "`doesNotContain`" - not sure it's the right name.
I know Laravel HTTPs test provide a `dontSee` method, so maybe `dontContain` ? But that sound weird.

Let me know,

**Comment by nunomaduro** [comment]
I think it makes sense, maybe something like `not()->contains()`?

**Comment by edgrosvenor** [comment]
I like the way that looks, but it might be a little harder to implement.

**Comment by SimoTod** [comment]
I think the main challenges with a chain-able `not()` are:
- people are used to dontXYZ()/doesntXYZ methods (not a big issue, just a small inconsistency with the existing framework)
- a dev could use not() at any positions of the chain but I'm not sure what `not()->in()`, `not->at()`, `not->first()`, etc should do. Are we expecting them to return a ViewAssertion containing everything but the elements which would be returned by `in()`, `at()`, `first()`, etc?
- if a user writes a custom macro, are we expecting not() to negate the result of that macro, if yes we should probably provide guidelines in the read me on how to write a custom macro.

@beNjiox In the meantime, you can achieve it with a Macro as you said but:
- assertions don't return `true/false`, they either return correctly or return an exception (that's the reason why negating contains wasn't working for you, it triggers the exception in both cases or you are just negating `$this` if `contains()` runs correctly)
- your macro should ideally return `$this` so it's chain-able like the other existing methods
- there is a function assert available which allows you to print the error message using the same format of the other existing assertions.

Your macro could be something like
```php
        ViewAssertion::macro('doesNotContain', function (string $text) {
            self::assert(function () use ($text) {
                Assert::assertStringNotContainsString((string) $text, $this->html);
            }, "Failed asserting that the text `$text` does not exist within %s.");

            return $this;
        });
```

**Comment by beNjiox** [comment]
Hey @SimoTod -

Thanks a lot for your answer.
I agree with your rational about `not()` - the behaviour might not be clear, and I too prefer the `doesNotX` syntax for readability and consistency with what already exist.

The reason why I thought Macro'ed assertions returned true or false was because of the test case for Macro there's [in the repository](https://github.com/nunomaduro/laravel-mojito/blob/master/tests/IsMacroable.php)
I probably misunderstood this.

I've tried your approach but it doesn't seem to work.
When using your exact code, and then use the new macro `doesNotContain` in my test, I get:

```
ErrorException : Undefined property: NunoMaduro\LaravelMojito\ViewAssertion::$html
```

I've been able to make it work after some digging, but not sure that's the proper way to do it

```php
class ViewAssertionProvider extends ServiceProvider
{
    public function boot()
    {
        ViewAssertion::macro('doesNotContain', function (string $text) {
            self::assert(function () use ($text) {
                Assert::assertStringNotContainsString((string) $text, $this->crawler->text());
            }, "Failed asserting that the text `$text` does not exist within %s.");

            return $this;
        });
    }
}
```

I've basically used `$this->crawler->text()` instead of the elegant `$this->html` you were suggesting.

Am I missing something?

Thanks

**Comment by SimoTod** [comment]
HI @beNjiox ,
the $html variable has been added only yesterday (sorry, I forgot to mention it). 
If you pull the latest version with `composer update nunomaduro/laravel-mojito` you should be able to use it.
Your macro is correct, too (you can also use '$this->crawler->outerHtml()` if you are interested in printing the html tags). Since it's a custom macro, the most important thing is that the error message makes sense to you. Glad you get it sorted. 👍

**Comment by beNjiox** [comment]
Ah yes, works perfectly.

I'll close the issue, thanks to the 2 of you.

I still think `doesNotContain` is a great candidate to be implemented within the package. If people get to this issue and are also interested, let me know and I'll happily PR something :-) 🚀
